feat(FeatureCard): add a feature card component
codse/animata pull request #266
Opened 2024-10-02 12:29 UTC by Aryan-AAP

https://github.com/user-attachments/assets/2fa27ba6-2541-4f3c-813d-dbab8082ff20

Done

2024-10-02 13:25 UTC, sudhashrestha requested changes

2024-10-02 13:25 UTC, sudhashrestha commented on content/docs/card/feature-card.mdx
> +```
```suggestion
<Step>Install dependencies</Step>

```bash
npm install framer-motion lucide-react
```
```
You don't need this step

2024-10-02 13:25 UTC, sudhashrestha commented on animata/card/feature-card.tsx
> +        <button key={platform.name} className={getButtonClasses(platform)}>
You can use tailwind group instead of custom state for tracking hover. Also, you can use the **cn** function utility for conditional classes.

2024-10-03 08:44 UTC, sudhashrestha commented
Hi @Aryan-AAP Please link the issue to this PR. Thanks

2024-10-03 12:39 UTC, hari commented
Closing this in favor of #277

2024-10-03 12:39 UTC, closed without merging