Feature component disclosure interaction
codse/animata pull request #278
Opened 2024-10-02 19:18 UTC by IngaleChinmay04

The DisclosureInteraction component is an interactive button that expands into a small sheet when clicked. This sheet provides six options (e.g., Project, Task, Note, etc.) and includes a close button to collapse the sheet back to its original state. The component features smooth animations for expanding and collapsing, and is styled using a clean and modern UI design.

Closes Issue: #271 

https://github.com/user-attachments/assets/89454af4-7770-478a-897e-93de17d1c737

2024-10-03 08:13 UTC, hari requested changes
We do not use `npm`, instead we use `yarn`. Also, you cannot downgrade the `next` version. Please remove `package-lock` and update PR.

2024-10-03 08:13 UTC, hari commented on animata/button/disclosure-interaction.tsx
> +          position: absolute;
Please use tailwindcss.

2024-10-03 08:13 UTC, hari commented on content/docs/button/disclosure-interaction.mdx
> +author: YourTwitterUsername
Twitter username is missing

2024-10-03 08:13 UTC, hari commented on content/docs/button/disclosure-interaction.mdx
> +
Remove unused steps

2024-10-03 08:13 UTC, hari commented on content/docs/button/disclosure-interaction.mdx
> +...Add appropriate credits here.
Update this

2024-10-03 08:14 UTC, hari commented
Please use 'lucide-react` icons and improve the animation as well :)

2024-10-03 11:12 UTC, IngaleChinmay04 commented
Okay I will work on the issues

2024-10-03 13:00 UTC, IngaleChinmay04 commented
I've resolved the requested changes, including Tailwind CSS adjustments, lucide-react icons, and animations. Please review the updates.



https://github.com/user-attachments/assets/dbeec3c6-0de5-487a-b315-8d1c483495d6

2024-10-03 13:10 UTC, IngaleChinmay04 commented
I mistakenly triggered the preview-deployment for this pull request. Could you please avoid approving the deployment or cancel the approval request?

2024-10-03 13:58 UTC, hari requested changes

2024-10-03 13:58 UTC, hari commented on content/docs/button/disclosure-interaction.mdx
> +
@IngaleChinmay04 you are missing other steps.

2024-10-03 13:58 UTC, hari commented on package.json
> +    "next": "13.4",
@IngaleChinmay04 Please undo this change (and yarn.lock) changes.

2024-10-03 13:58 UTC, hari commented
@IngaleChinmay04 The deployment is automatic and it's nothing to worry.

2024-10-03 18:32 UTC, IngaleChinmay04 commented
I have updated the package.json and added yarn.lock and also steps in mdx file.
Apologies for the inconvenience with these small changes.

2024-10-04 00:47 UTC, hari commented on yarn.lock
@IngaleChinmay04 `yarn.lock` is still here. This file shouldn't change as you haven't added any new dependencies.

2024-10-04 06:16 UTC, IngaleChinmay04 commented
Should I remove the yarn.lock file?

2024-10-04 08:17 UTC, IngaleChinmay04 commented
I have replcaed the yarn.lock file which was there in main branch to avoid changes

2024-10-05 02:14 UTC, hari approved these changes

2024-10-05 02:15 UTC, hari commented
Your PR should not have the `yarn.lock` file. The build is failing.

```
Run yarn install --immutable
➤ YN0000: · Yarn [4](https://github.com/codse/animata/actions/runs/11176462640/job/31069877354?pr=278#step:6:5).2.2
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 0s 2[8](https://github.com/codse/animata/actions/runs/11176462640/job/31069877354?pr=278#step:6:10)3ms
➤ YN0000: ┌ Post-resolution validation
Post-resolution validation
➤ YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 387ms
```

2024-10-05 15:35 UTC, hari commented
@IngaleChinmay04 please create a fresh PR with only those 3 files. Make sure to pull the latest main first. I am closing this one.

2024-10-05 15:35 UTC, closed without merging