feat(reminder-scheduler): adds reminder-scheduler component
codse/animata pull request #313
Opened 2024-10-04 15:12 UTC by prince981620

hey @hari apologies for my previous PR i mistakenly created branch from my old branch.
please review.
thank-you

2024-10-05 02:12 UTC, hari requested changes

2024-10-05 02:12 UTC, hari commented on animata/card/reminder-scheduler.tsx
> +  }, [check]);
you need to clear timeout on unmount.

2024-10-05 02:12 UTC, hari commented on content/docs/card/reminder-scheduler.mdx
> +```
remove the step if it is not necessary

2024-10-05 02:12 UTC, hari commented on content/docs/card/reminder-scheduler.mdx
> +````
extra backtick

2024-10-05 02:12 UTC, hari commented on animata/card/reminder-scheduler.tsx
> +    console.log("Toggled");
remove log

2024-10-05 02:12 UTC, hari commented on animata/card/reminder-scheduler.tsx
> +  const daysOfWeek = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];
you can move this out of the component

2024-10-05 02:12 UTC, hari commented on animata/card/reminder-scheduler.tsx
> +    isRepeating ? setSelectedDays(["Th", "Fr", "Su"]) : setSelectedDays(["Mo", "We", "Sa"]);
you don't need a state for this, simply use a local variable on top `const selectedDays = isRepeating ? ...`

2024-10-05 02:12 UTC, hari commented on animata/card/reminder-scheduler.tsx
> +              check={selectedDays.includes(day)}
you can use `Set` instead of `Array` for `selectedDays`.

2024-10-06 13:55 UTC, hari commented
@prince981620 Could you merge the latest main on your branch?

2024-10-06 15:33 UTC, hari commented on content/docs/card/reminder-scheduler.mdx
> +
`<Steps>` is missing here @prince981620

2024-10-07 06:45 UTC, prince981620 commented
> @prince981620 Could you merge the latest main on your branch?

merged and pushed again please review.

2024-10-09 23:49 UTC, hari approved these changes

2024-10-09 23:50 UTC, merged

2024-10-23 12:58 UTC, prince981620 commented
hey @sudhashrestha i have already completed #296 and this also got merged: apologies for not mentioning it up there