feat: add Music Stack Interaction widget
codse/animata pull request #314
Opened 2024-10-04 17:21 UTC by mohitahlawat2001

#273 

https://github.com/user-attachments/assets/c436143f-be4e-4ac5-9cd9-ec292a46d8d3

2024-10-05 02:07 UTC, hari requested changes

2024-10-05 02:07 UTC, hari commented on animata/widget/music-stack-interaction.tsx
> +
@mohitahlawat2001 This is not animating correctly.

The easy way is to use `framer-motion` and animate layout.

But if you want, you can achieve this using CSS only, make sure that you are rendering albums only once (i.e. `albums.map` part) and then conditionally setting the styles. Both conditions should have all the required properties set for the animation to work nicely.

2024-10-05 02:07 UTC, hari commented on animata/widget/music-stack-interaction.tsx
> +const carouselBackgroundStyles = {
you can add type annotations here instead of adding them on each property:

`const carouselBackgroundStyles: React.CSSProperties`

2024-10-05 02:07 UTC, hari commented on animata/widget/music-stack-interaction.tsx
> +                  </div>
Please play with line-height and font-size to make it look better. I think we don't need `text-lg` here.

2024-10-05 15:38 UTC, hari commented
@mohitahlawat2001 Instead of fixing on `animata/widget/music-stack-interaction.tsx` you modified the `animata/widget/music-stack-interaction.stories.tsx`. Please move the logic to `music-stack-interaction.tsx` and update the story.

2024-10-05 15:40 UTC, mohitahlawat2001 commented
doing in 10 minutes

2024-10-05 15:51 UTC, mohitahlawat2001 commented
https://github.com/user-attachments/assets/0b1f90b1-b84a-47d3-afb7-33bef53bbc70

2024-10-06 16:01 UTC, hari commented
@mohitahlawat2001 The animation is glitchy, use can fix this by changing the style values instead of using the layout animation.

2024-10-06 16:06 UTC, mohitahlawat2001 commented
Please give me more idea which value I have to change,  I am still new to
designing animation

On Sun, Oct 6, 2024, 9:31 PM Hari Lamichhane ***@***.***>
wrote:

> @mohitahlawat2001 <https://github.com/mohitahlawat2001> The animation is
> glitchy, use can fix this by changing the style values instead of using the
> layout animation.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/codse/animata/pull/314#issuecomment-2395489655>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQVYO7T5VD63LUEPCQETJTZ2FNHPAVCNFSM6AAAAABPMJGYDWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGQ4DSNRVGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-07 05:28 UTC, mohitahlawat2001 commented
i make some change and make animation smooth ,

2024-10-15 11:06 UTC, mohitahlawat2001 commented
i made change for solving error

2024-10-17 07:24 UTC, hari approved these changes

2024-10-17 13:42 UTC, merged