feat(pills): add scattered pills feature and resolve issue #238
codse/animata pull request #336
Opened 2024-10-05 11:17 UTC by raghav3615

Solve issue #238 - feat(pills): Scattered Pills 
@sudhashrestha kindly review it 

Checklist:
I have read and followed the contributing guidelines.
I have developed the component according to the requirements.
I have tested the component across different browsers and screen sizes.
I have documented the component for future reference.
I have submitted a pull request with appropriate labels and referenced this issue number.

2024-10-05 11:20 UTC, hari commented
@raghav3615 this should be inside ‘feature cards’

2024-10-05 11:25 UTC, hari requested changes

2024-10-05 11:25 UTC, hari commented on animata/pills/scattered-pills.tsx
> +  const [hoveredPills, setHoveredPills] = useState<number[]>([]);
Actually, you don't need these states. The pills become straight when the parent div is hovered and are rotated by default.

2024-10-05 11:25 UTC, hari commented on content/docs/pills/scattered-pills.mdx
> +author: YourTwitterUsername
Your twitter username

2024-10-05 11:25 UTC, hari commented on animata/pills/scattered-pills.tsx
> +        <motion.div
You can achieve this use CSS and don't need to use framer-motion.

2024-10-05 13:52 UTC, raghav3615 commented
@hari can you review it now

2024-10-05 19:01 UTC, raghav3615 commented
@hari kindly review this

2024-10-06 11:52 UTC, hari approved these changes

2024-10-06 11:58 UTC, hari commented on content/docs/card/scattered-pills.mdx
> +
`<Steps>` is missing here @raghav3615

2024-10-06 14:08 UTC, hari commented
@raghav3615 could you please sync your branch with the latest changes from the main?

2024-10-06 14:12 UTC, raghav3615 commented
@hari done

2024-10-06 16:00 UTC, hari requested changes

2024-10-06 16:00 UTC, hari commented on animata/card/scattered-pills.tsx
> +    <div className="flex h-screen flex-col items-center justify-start space-y-3 bg-transparent pt-24">
@raghav3615 please replace `h-screen` with `h-fit`

2024-10-06 16:03 UTC, raghav3615 commented on animata/card/scattered-pills.tsx
> +    <div className="flex h-screen flex-col items-center justify-start space-y-3 bg-transparent pt-24">
@hari done

2024-10-06 16:41 UTC, hari approved these changes

2024-10-07 03:37 UTC, hari commented
@raghav3615 The implementation is still not correct. You don't need any state for that, I understand it could be not very clear from the video. Here's how it should work

1. The items are rotated by default
2. On group hover, the rotation of the item should be set to 0
3. When hovering over each item, they need to scale.

Also, please use symmetric vertical padding i.e. `py-24` instead of `pt-24`, and reduce the value in small devices.

That is all we need and can be accomplished using CSS only.

2024-10-09 23:55 UTC, hari requested changes
Please check my comment above :)

2024-10-23 11:57 UTC, sudhashrestha commented
Hi @raghav3615 

I hope you're doing well! Since it's been a while since this PR was reviewed, I wanted to check in and see if you're still planning to work on it. If so, could you kindly share an update by tomorrow?

If I don't hear back by then, I’ll unassign the issue to allow others to take it up.

Thanks for your understanding!

2025-04-25 07:55 UTC, closed without merging