feat(fluid-tabs): added fluid tabs component
codse/animata pull request #351
Opened 2024-10-07 16:09 UTC by Rudra-Sankha-Sinhamahapatra

Created the fluid tabs component
Fixes #325 

https://github.com/user-attachments/assets/d1e7b3db-12d0-4c42-80c6-a1499402b0b1

2024-10-08 14:04 UTC, Rudra-Sankha-Sinhamahapatra commented
@hari  can you please review this PR?

2024-10-08 16:17 UTC, hari requested changes

2024-10-08 16:17 UTC, hari commented on animata/card/fluid-tabs.tsx
> +    <div className="flex h-screen items-center justify-center bg-gray-100">
Please remove `h-screen`

2024-10-08 16:17 UTC, hari commented on animata/card/fluid-tabs.tsx
> +            whileTap={{ scale: 0.95 }}
Please remove these two.

2024-10-08 16:17 UTC, hari commented on animata/card/fluid-tabs.tsx
> +            <span className="flex items-center space-x-2">
You can remove this span and use the children directly inside the button. The icon and span are not aligned vertically.

2024-10-08 19:55 UTC, Rudra-Sankha-Sinhamahapatra commented
![image](https://github.com/user-attachments/assets/24e51778-69cc-44c9-a83e-79ead86cd123)
@hari done

2024-10-08 19:57 UTC, Rudra-Sankha-Sinhamahapatra commented on animata/card/fluid-tabs.tsx
> +    <div className="flex h-screen items-center justify-center bg-gray-100">
removed sir

2024-10-10 00:06 UTC, hari requested changes
@Rudra-Sankha-Sinhamahapatra Maybe blurring the other items rather than the clicked one will look better? Please check and make the changes if it feels right.

2024-10-10 00:06 UTC, hari commented on animata/card/fluid-tabs.tsx
> +    icon: <Landmark size={18} className="mr-2 mt-1" />,
Please remove `mr-1 mt-1` from all three icons.

2024-10-10 00:06 UTC, hari commented on animata/card/fluid-tabs.tsx
> +            className={`relative z-10 flex w-full items-center justify-center px-5 py-3 text-sm font-bold transition-colors duration-300 ${
Add `gap-1.5` on the button className.

2024-10-10 23:17 UTC, Rudra-Sankha-Sinhamahapatra commented on animata/card/fluid-tabs.tsx
> +            className={`relative z-10 flex w-full items-center justify-center px-5 py-3 text-sm font-bold transition-colors duration-300 ${
done

2024-10-10 23:17 UTC, Rudra-Sankha-Sinhamahapatra commented on animata/card/fluid-tabs.tsx
> +    icon: <Landmark size={18} className="mr-2 mt-1" />,
done

2024-10-10 23:19 UTC, Rudra-Sankha-Sinhamahapatra commented
@hari sir i tried your suggestions but i think the current animation which was in the issue looks better, so i am currently not changing anything else ... but i have made those ui changes you mentioned..kindly check it please

2024-10-11 20:22 UTC, Rudra-Sankha-Sinhamahapatra commented
@hari can you check now please

2024-10-15 09:58 UTC, hari approved these changes

2024-10-15 09:58 UTC, merged