feat(transaction-list): adds transaction-list
codse/animata pull request #352
Opened 2024-10-07 17:06 UTC by prince981620

hey @hari i have added Transaction List #319 , please review

2024-10-08 16:25 UTC, hari requested changes
Please make the spacing even and improve the gap between text in the detail body.

2024-10-08 16:25 UTC, hari commented on animata/list/transaction-list.tsx
> +        animate={{
Please add `initial` prop as well so that the list doesn't animate initially.

2024-10-08 17:34 UTC, prince981620 commented
> Please make the spacing even and improve the gap between text in the detail body.
 hey @hari i have added even spacing and also improved the gap . please review

2024-10-15 09:58 UTC, hari approved these changes

2024-10-15 09:59 UTC, merged