feat(container): add interactive nav bar
codse/animata pull request #370
Opened 2024-10-16 20:31 UTC by spartanns

Closes #274

2024-10-17 13:49 UTC, hari commented
@spartanns Please push the related yarn.lock file as well, you have installed the dependency but yarn.lock is missing.

2024-10-17 14:04 UTC, spartanns commented
Pushed.

2024-10-17 14:13 UTC, spartanns commented
It seems like I need to add the components/ui/navigation-menu.tsx... How do I do this? It's listed in .eslintignore, and if I remove it, the linter will fail.

2024-10-21 04:07 UTC, hari commented
@spartanns you can commit that using `-n` flag.

2024-10-21 04:13 UTC, spartanns commented
Done.

2024-10-21 15:20 UTC, hari commented
@spartanns the colors are wrong in dark mode.

2024-10-21 15:22 UTC, hari requested changes

2024-10-21 15:22 UTC, hari commented on content/docs/container/interactive-nav-bar.mdx
> +...Add appropriate credits here.
Update this

2024-10-21 15:22 UTC, hari commented on content/docs/container/interactive-nav-bar.mdx
> +
Remove this as it is not needed

2024-10-21 15:22 UTC, hari commented on content/docs/container/interactive-nav-bar.mdx
> +npm install framer-motion lucide-react
Update dependencies

2024-10-21 16:02 UTC, spartanns commented
Applied some fixes... Let me know if you want the carets from the nav buttons removed.

2024-10-23 08:13 UTC, hari commented
@spartanns I cannot interact with the items, if I move the mouse to the nav content, it closes. Also, if I click to open the item, it close as well.

2025-04-25 07:55 UTC, closed without merging