Feature card - Customer Rating (Resolves #216)
codse/animata pull request #378
Opened 2024-10-24 15:04 UTC by codeza-ai

This closes #216 

## Checklist 

-   [x] Completed Task
-   [x] I have read and followed the contributing guidelines.
-   [x] I have developed the component according to the requirements.
-   [x] I have tested the component across different browsers and screen sizes.
-   [x] I have documented the component for future reference.
-   [x] I have submitted a pull request with appropriate labels and referenced this issue number.

## Screenshots -

### Normal
![Screenshot 2024-10-24 195226](https://github.com/user-attachments/assets/b2284fd4-3d89-4499-80e5-47269cd5df83)
### Hover 
![Screenshot 2024-10-24 195239](https://github.com/user-attachments/assets/2b3bc850-b678-43c8-8ec3-cea0b4d174e9)

2024-10-25 04:38 UTC, codeza-ai commented
@sudhashrestha How can I add reviewer to it?

2024-10-28 04:21 UTC, hari requested changes

2024-10-28 04:21 UTC, hari commented on content/docs/card/customer-rating.mdx
> +...Add appropriate credits here.
Please remove this line

2024-10-28 04:21 UTC, hari commented on content/docs/card/customer-rating.mdx
> +author: [Darshan Odedara](https://github.com/codeza-ai)
this should twitter username

2024-10-28 04:21 UTC, hari commented on animata/card/customer-rating.tsx
> +      onMouseLeave={() => setHovered(false)}
you don't need state for this and can use `group` hover from tailwindcss.

2025-04-25 07:55 UTC, closed without merging